CREATE TABLE `CashOperationApprovalRequest` (
  `id` VARCHAR(191) NOT NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
  `requestedById` VARCHAR(191) NOT NULL,
  `reviewedById` VARCHAR(191) NULL,
  `occurredAt` DATETIME(3) NOT NULL,
  `direction` VARCHAR(191) NOT NULL,
  `category` VARCHAR(191) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `currency` VARCHAR(191) NOT NULL DEFAULT 'USD',
  `fxRateUsdToCdf` DOUBLE NOT NULL,
  `amountUsd` DOUBLE NOT NULL,
  `amountCdf` DOUBLE NOT NULL,
  `method` VARCHAR(191) NOT NULL,
  `reference` VARCHAR(191) NULL,
  `description` TEXT NOT NULL,
  `cashDesk` VARCHAR(191) NOT NULL,
  `projectedDailyOutflowUsd` DOUBLE NOT NULL,
  `dailyOutflowCapUsd` DOUBLE NOT NULL,
  `reason` TEXT NULL,
  `approvedAt` DATETIME(3) NULL,
  `rejectedAt` DATETIME(3) NULL,
  `executedAt` DATETIME(3) NULL,
  `executedCashOperationId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  UNIQUE INDEX `CashOperationApprovalRequest_executedCashOperationId_key`(`executedCashOperationId`),
  INDEX `CashOperationApprovalRequest_status_createdAt_idx`(`status`, `createdAt`),
  INDEX `CashOperationApprovalRequest_requestedById_idx`(`requestedById`),
  INDEX `CashOperationApprovalRequest_reviewedById_idx`(`reviewedById`),
  INDEX `CashOperationApprovalRequest_cashDesk_createdAt_idx`(`cashDesk`, `createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;